[package]
name = "sendmail2http"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.12.28", features = ["blocking", "json"] }
serde_json = "1.0.148"
shell-escape = "0.1.5"
